# Generated by Django 4.2.2 on 2023-06-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_breed_friendliness_remove_breed_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='exerciseneeds',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='friendliness',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='sheddingamount',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='trainability',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=10, null=True),
        ),
    ]
